name: Bug Report
labels: "bug"
description: Report a problem you're having
body:
- type: input
  id: distribution
  attributes:
    label: Linux distribution
    placeholder: e.g., Bazzite, Arch Linux, Chimera Linux
  validations:
    required: true
  
- type: dropdown
  id: installation
  attributes:
      label: Installation method
      options:
        - Flatpak
        - Distribution Package
        - Source
  validations:
    required: true

- type: input
  id: version
  attributes:
    label: Vinegar version
    description: If you're on Flatpak, put the output of `flatpak info -c org.vinegarhq.Vinegar` here.
  validations:
    required: true
    
- type: textarea
  id: problem
  attributes:
    label: What problem did you encounter?
    description: >
      Provide a description of the problem you're facing.
      Don't forget to attach any log files and screenshots.
      Logs can be found by clicking 'Open Logs' at the menu in the top-right inside Vinegar's settings page.
  
  validations:
    required: true
