name: Bug Report
labels: "bug"
description: Report an issue you're having
body:
  - type: checkboxes
    id: guidelines-confirmation
    attributes:
      label: Carefully follow the checklist to get started with the bug report
      options:
        - label: I have checked that my issue has not already been reported or addressed.
          required: true
        - label: I agree to explain the bug exactly as-is, without using any AI-generated summaries or explanations.
          required: true
        - label: I agree that I just checked every box without actually reading anything.
          required: false
  - type: input
    id: kernel
    attributes:
      label: Kernel version
      description: If you don't know which version of the Linux kernel you're using, add the output of running `uname -r` here.
      placeholder: e.g. 7.0.9-arch1-1
    validations:
      required: true
  - type: dropdown
    id: installation
    attributes:
      label: Installation method
      options:
        - Flatpak
        - Distribution-specific package
        - Source
    validations:
      required: true
  - type: input
    id: vinegar
    attributes:
      label: Vinegar version
      description: >
        If you don't know which version of Vinegar you're using, add the output of running `flatpak info org.vinegarhq.Vinegar | sed '/Version:/!d;s/^[[:space:]]*Version:[[:space:]]//'` here.
        Users of distribution-specific packages may need to consult the manual of their package manager to get the version.
        If you built Vinegar from source, add the output of running `git rev-parse HEAD` inside its source directory here.
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: What issue did you encounter?
      description: >
        Provide a detailed description of the issue you're facing.
        **Attaching the latest log file generated by Vinegar is mandatory.**
        Logs can be found inside of `~/.var/app/org.vinegarhq.Vinegar/cache/vinegar/logs` or `~/.cache/vinegar/logs` when not using the Flatpak.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps for reproducing the issue
      description: Steps are to be given in chronological order.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
