name: Feature request
labels: "enhancement"
description: Suggest a feature that should be added
assignees:
  - sewnie
body:
  - type: checkboxes
    attributes:
      label: Before Creating the Enhancement Request
      description: >
        Most of issues should be classified as bug or feature request. An issue should be considered as an enhancement when it proposes improvements to
        existing functionality or user experience, without necessarily introducing new features or fixing existing bugs.
      options:
        - label: >
            I have confirmed that this should be classified as an enhancement rather than a bug/feature.
          required: true

  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      placeholder: >
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the Solution you'd Like
      placeholder: >
        A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe Alternatives you've considered
      placeholder: >
        List any alternative enhancements or implementations you have considered, and explain why they may not be as effective or appropriate.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      placeholder: >
        Add any relevant context, screenshots, prototypes, or other supplementary information to help illustrate the enhancement.
    validations:
      required: false
