# Get rid of existing vinegar install, along with old binaries generated by make
sudo make uninstall
rm -f robloxmutexer.exe
rm -f vinegar

#Create a new build of vinegar with the current source code, then install it
make
sudo make install